// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250523052741_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ApprovalRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApproverRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("ApproverRoleId1")
                        .HasColumnType("int");

                    b.Property<int?>("Area")
                        .HasColumnType("int");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProjectTypeId")
                        .HasColumnType("int");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverRoleId");

                    b.HasIndex("ApproverRoleId1");

                    b.HasIndex("Area");

                    b.HasIndex("AreaId");

                    b.HasIndex("ProjectTypeId");

                    b.HasIndex("Type");

                    b.ToTable("ApprovalRule");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApproverRoleId = 1,
                            MaxAmount = 100000m,
                            MinAmount = 0m,
                            StepOrder = 1
                        },
                        new
                        {
                            Id = 2L,
                            ApproverRoleId = 2,
                            MaxAmount = 20000m,
                            MinAmount = 5000m,
                            StepOrder = 2
                        },
                        new
                        {
                            Id = 3L,
                            ApproverRoleId = 2,
                            Area = 2,
                            MaxAmount = 20000m,
                            MinAmount = 0m,
                            StepOrder = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 4L,
                            ApproverRoleId = 3,
                            MaxAmount = 0m,
                            MinAmount = 20000m,
                            StepOrder = 3
                        },
                        new
                        {
                            Id = 5L,
                            ApproverRoleId = 2,
                            Area = 1,
                            MaxAmount = 0m,
                            MinAmount = 5000m,
                            StepOrder = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 6L,
                            ApproverRoleId = 1,
                            MaxAmount = 10000m,
                            MinAmount = 0m,
                            StepOrder = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 7L,
                            ApproverRoleId = 4,
                            Area = 2,
                            MaxAmount = 10000m,
                            MinAmount = 0m,
                            StepOrder = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 8L,
                            ApproverRoleId = 2,
                            Area = 2,
                            MaxAmount = 30000m,
                            MinAmount = 10000m,
                            StepOrder = 2
                        },
                        new
                        {
                            Id = 9L,
                            ApproverRoleId = 3,
                            Area = 3,
                            MaxAmount = 0m,
                            MinAmount = 30000m,
                            StepOrder = 2
                        },
                        new
                        {
                            Id = 10L,
                            ApproverRoleId = 1,
                            MaxAmount = 50000m,
                            MinAmount = 0m,
                            StepOrder = 1,
                            Type = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.ApprovalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("ApprovalStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rejected"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Observed"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ApproverRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApproverRole");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Líder de Área"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gerente"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Director"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Comité Técnico"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Area");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Finanzas"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tecnología"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Operaciones"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProjectApprovalStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("ApprovalStatusId")
                        .HasColumnType("int");

                    b.Property<int>("ApproverRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("ApproverUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectProposalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatusId");

                    b.HasIndex("ApproverRoleId");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("ProjectProposalId");

                    b.HasIndex("Status");

                    b.ToTable("ProjectApprovalStep");
                });

            modelBuilder.Entity("Domain.Entities.ProjectProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ApprovalStatusId")
                        .HasColumnType("int");

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CreateBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstimatedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EstimatedDuration")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalStatusId");

                    b.HasIndex("Area");

                    b.HasIndex("AreaId");

                    b.HasIndex("CreateBy");

                    b.HasIndex("ProjectTypeId");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("ProjectProposal");
                });

            modelBuilder.Entity("Domain.Entities.ProjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("ProjectType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mejora de Procesos"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Innovación y Desarrollo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Infraestructura"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Capacitación Interna"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApproverRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverRoleId");

                    b.HasIndex("Role");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jferreyra@unaj.com",
                            Name = "José Ferreyra",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            Email = "alucero@unaj.com",
                            Name = "Ana Lucero",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "gmolinas@unaj.com",
                            Name = "Gonzalo Molinas",
                            Role = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "lolivera@unaj.com",
                            Name = "Lucas Olivera",
                            Role = 3
                        },
                        new
                        {
                            Id = 5,
                            Email = "dfagundez@unaj.com",
                            Name = "Danilo Fagundez",
                            Role = 4
                        },
                        new
                        {
                            Id = 6,
                            Email = "ggalli@unaj.com",
                            Name = "Gabriel Galli",
                            Role = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.ApprovalRule", b =>
                {
                    b.HasOne("Domain.Entities.ApproverRole", "ApproverRoleNavigation")
                        .WithMany()
                        .HasForeignKey("ApproverRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ApproverRole", null)
                        .WithMany("ApprovalRules")
                        .HasForeignKey("ApproverRoleId1");

                    b.HasOne("Domain.Entities.Area", "AreaNavigation")
                        .WithMany()
                        .HasForeignKey("Area")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Area", null)
                        .WithMany("ApprovalRules")
                        .HasForeignKey("AreaId");

                    b.HasOne("Domain.Entities.ProjectType", null)
                        .WithMany("AppovalRules")
                        .HasForeignKey("ProjectTypeId");

                    b.HasOne("Domain.Entities.ProjectType", "TypeNavigation")
                        .WithMany()
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApproverRoleNavigation");

                    b.Navigation("AreaNavigation");

                    b.Navigation("TypeNavigation");
                });

            modelBuilder.Entity("Domain.Entities.ProjectApprovalStep", b =>
                {
                    b.HasOne("Domain.Entities.ApprovalStatus", null)
                        .WithMany("ProjectApprovalSteps")
                        .HasForeignKey("ApprovalStatusId");

                    b.HasOne("Domain.Entities.ApproverRole", "ApproverRoleNavigation")
                        .WithMany()
                        .HasForeignKey("ApproverRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "ApproverUserNavigation")
                        .WithMany()
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.ProjectProposal", "ProjectProposalNavigation")
                        .WithMany()
                        .HasForeignKey("ProjectProposalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ApprovalStatus", "StatusNavigation")
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApproverRoleNavigation");

                    b.Navigation("ApproverUserNavigation");

                    b.Navigation("ProjectProposalNavigation");

                    b.Navigation("StatusNavigation");
                });

            modelBuilder.Entity("Domain.Entities.ProjectProposal", b =>
                {
                    b.HasOne("Domain.Entities.ApprovalStatus", null)
                        .WithMany("ProjectProposals")
                        .HasForeignKey("ApprovalStatusId");

                    b.HasOne("Domain.Entities.Area", "AreaNavigation")
                        .WithMany()
                        .HasForeignKey("Area")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Area", null)
                        .WithMany("ProjectProposals")
                        .HasForeignKey("AreaId");

                    b.HasOne("Domain.Entities.User", "CreateByNavigation")
                        .WithMany()
                        .HasForeignKey("CreateBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProjectType", null)
                        .WithMany("ProjectProposals")
                        .HasForeignKey("ProjectTypeId");

                    b.HasOne("Domain.Entities.ApprovalStatus", "StatusNavigation")
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProjectType", "TypeNavigation")
                        .WithMany()
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AreaNavigation");

                    b.Navigation("CreateByNavigation");

                    b.Navigation("StatusNavigation");

                    b.Navigation("TypeNavigation");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.ApproverRole", null)
                        .WithMany("Users")
                        .HasForeignKey("ApproverRoleId");

                    b.HasOne("Domain.Entities.ApproverRole", "RoleNavigation")
                        .WithMany()
                        .HasForeignKey("Role")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoleNavigation");
                });

            modelBuilder.Entity("Domain.Entities.ApprovalStatus", b =>
                {
                    b.Navigation("ProjectApprovalSteps");

                    b.Navigation("ProjectProposals");
                });

            modelBuilder.Entity("Domain.Entities.ApproverRole", b =>
                {
                    b.Navigation("ApprovalRules");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Area", b =>
                {
                    b.Navigation("ApprovalRules");

                    b.Navigation("ProjectProposals");
                });

            modelBuilder.Entity("Domain.Entities.ProjectType", b =>
                {
                    b.Navigation("AppovalRules");

                    b.Navigation("ProjectProposals");
                });
#pragma warning restore 612, 618
        }
    }
}
